services:
  - docker

install:
  - docker pull jjmerelo/test-perl6
  - docker images
  - docker run -t --entrypoint="/bin/sh" jjmerelo/test-perl6 -c "perl6 --version; which zef "

script: 
  - docker run -t -v  $TRAVIS_BUILD_DIR:/test jjmerelo/test-perl6

